use std::env;

fn generate_qivm_runtime_headers() {
    use cbindgen::{Config, Language};
    let target_path = format!("target/{}/include/qivm/runtime.h", &env::var("PROFILE").unwrap());
    let config = Config {
        language: Language::C,
        cpp_compat: true,
        tab_width: 4,
        autogen_warning: Some("/* [WARNING] This file is autogenerated by program. Don't modify this manually. */".to_string()),
        include_guard: Some("QIVM_RUNTIME_H".to_string()),
        documentation: true,
        ..Default::default()
    };
    cbindgen::Builder::new()
        .with_crate(env::var("CARGO_MANIFEST_DIR").unwrap())
        .with_config(config)
        .generate()
        .expect("Unable to generate bindings")
        .write_to_file(target_path);
}

fn main() {
    println!("cargo:rustc-link-arg=-Wl,-rpath=$ORIGIN");
    println!("cargo:rustc-cfg=static_link_backend");
    generate_qivm_runtime_headers();
}